---
title: "Results Section"
output:
  html_document:
    df_print: paged
---

## Data Preparation

```{r message=FALSE}
#Load functions
#Source functions and packages
source("~/covid_simulation/Kin_death/01_load_functions.R")
source('~/covid_simulation/Kin_death/functions_bereavement.R')

#Require this additional packages
require(broom)
require(countrycode)
require(ggrepel)
require(viridis)
require(kableExtra)

#Load data: currently, this points to the latest version with data for the first wave
data <- get(load(file = "~/covid_simulation/Data/final_data_firstwave_updated.RData"))
```

```{r}
#Find numbers for indices for each country
indices <- data$numbers %>%
  group_by(country) %>%
  summarize(max_index = min(nsims))
```

```{r}
#Burden of bereavement object
kin_ebr <-data$kin_bb %>%
  full_join(., indices, by = c("country" = "country")) %>%
  filter(!is.na(scenario)) %>% 
  mutate(sex = ifelse(grepl("f1", category), "F", "M"),
         age = gsub("f[0-1]{1}", "", category),
         category = NULL) %>%
  ungroup() %>%
  group_by(country, scenario, sex, age, kintype) %>%
  mutate(index = row_number(), category = NULL) %>%
  filter(index <= max_index) %>%
  ungroup() %>%
  pivot_wider(id_cols = c("country", "sex", "age", "kintype", "index"), 
              names_from = "scenario", 
              values_from = c("mean_post_all", "mean_pre_all", "mean_pre_with", "sd_pre_with", "n_withkin", 
                              "mean_post_with", "sd_post_with", "sim.id", "n_losekin", "n_total")) %>%
  mutate(bereavement_covid = (mean_pre_with_covid - mean_post_with_covid),
         bereavement_other = (mean_pre_with_other - mean_post_with_other),
         n_withkin = (n_withkin_covid + n_withkin_other)/2,
         n_total = (n_total_covid + n_total_other)/2,
         pc_withkin = (n_withkin/n_total)*100,
         probloss_covid = 100*(n_losekin_covid/n_withkin_covid),
         probloss_other = 100*(n_losekin_other/n_withkin_other),
         probloss_rel_diff = 100*(probloss_covid - probloss_other)/probloss_other,
         probloss_abs_diff = probloss_covid - probloss_other,
         probloss_abs_diff_adj = probloss_abs_diff*pc_withkin/100,
         probloss_other_adj = (probloss_other*(n_withkin_other/n_total_other))/100,
         ccode = countrycode(gsub("_", " ", country), 
                             origin = 'country.name', destination = 'iso3c'))
```

```{r}
# Kin ratio object
  kin_structure <- data$kin_ratio %>%
    full_join(., indices, by = c("country" = "country")) %>%
    filter(!is.na(scenario)) %>% 
    mutate(sex = ifelse(grepl("f1", category), "F", "M"),
           age = gsub("f[0-1]{1}", "", category),
           category = NULL) %>%
    ungroup() %>%
    group_by(country, scenario, sex, age, kintype) %>%
    mutate(index = row_number(), category = NULL) %>%
    filter(index <= max_index) %>%
    ungroup() %>%
    pivot_wider(id_cols = c("country", "sex", "age", "kintype", "index"), 
                names_from = "scenario", 
                values_from = c("count_all", "sd_all", "count_female", "count_male",
                                "count_65plus", "count_below65", "n_egos", "sim.id")) %>%
    mutate(ccode = countrycode(gsub("_", " ", country), 
                               origin = 'country.name', destination = 'iso3c'),
           count_all_diff = count_all_covid - count_all_other)
```

```{r}
#Death rates object
  death_rates <- data$death_rates %>%
  full_join(., indices, by = c("country" = "country")) %>%
  filter(!is.na(scenario)) %>% 
  mutate(sex = ifelse(fem == 1, "F", "M")) %>%
  ungroup() %>%
  group_by(country, scenario, sex, age) %>%
  mutate(index = row_number(), fem = NULL) %>%
  filter(index <= max_index) %>%
  ungroup() %>%
  pivot_wider(id_cols = c("country", "sex", "age", "index"), 
              names_from = "scenario", 
            values_from = c("n_num", "n_den", "value", "sim.id")) 
```

```{r}
  #Object used for excess mortality analysis
  em <- death_rates %>%
  filter(age %ni% c("all_sum", "all_mid")) %>%
  mutate(age_interval = if_else(age %in% c("0-14"), "0-14", 
         if_else(age %in% c("65+"), "65+", "15-64"))) %>%
  ungroup() %>%
  group_by(index, country, sim.id_covid, sim.id_other, age_interval) %>%
  summarize(n_num_covid = sum(n_num_covid, na.rm = T),
            n_num_other = sum(n_num_other, na.rm = T)) %>%
    mutate(em = 100*((n_num_covid - n_num_other)/n_num_other),
           em = if_else(em == Inf, NaN, em))
```

```{r}
  #Object used for excess mortality analysis
  age_str_indiv <- death_rates %>%
  filter(age %ni% c("all_sum", "all_mid")) %>%
  ungroup() %>%
  group_by(index, country, sim.id_covid, sim.id_other, age, sex) %>%
  summarize(n_den_covid = sum(n_den_covid, na.rm = T),
            n_den_other = sum(n_den_other, na.rm = T)) %>%
    mutate(n_den = (n_den_covid + n_den_other)/2)

age_str_total <- age_str_indiv %>%
  ungroup() %>%
  group_by(index, country, sim.id_covid, sim.id_other, sex) %>%
  summarize(total = sum(n_den))

age_str_15 <- age_str_indiv %>%
  ungroup() %>%
  filter(age %in% c("15-29", "30-44", "45-64")) %>%
  group_by(index, country, sim.id_covid, sim.id_other, sex) %>%
  summarize(total_15 = sum(n_den))

age_str <- merge(age_str_indiv, merge(age_str_total, age_str_15))


age_str <- age_str %>%
  mutate(pc_age = 100*(n_den/total))
```

```{r}
#STMF mortality rates
#Calculate STMF excess mortality based on the code in MakeFactor.R, with modifications
 stmf <- fread("~/covid_simulation/Rcode/stmf-mar9-run.csv", stringsAsFactors = F)

  names(stmf) <- tolower(names(stmf)) #Make names lowercase

  #Keeping countries that only have data for 2020
  keepcountry <- unique(stmf$countrycode[which(stmf$year == 2020)])

  #Pivoting the STMF data into long format
  adj.total <- stmf %>%
    dplyr::select(-c(split, splitsex, forecast)) %>% #removing variables
    filter(countrycode %in% keepcountry) %>%
    pivot_longer(-c(year, week, countrycode, sex), 
                 names_to = c("type", "age"), values_to = "rate", names_sep = 1) %>% #pivoting
    pivot_wider(names_from = "type", values_from = "rate") %>%
    mutate(death_count = d, #renaming and generating new versions of variables
           death_rate = r,
           age = gsub("85p", "85-99", gsub("_", "-", age)),
           age_int = age,
           age = if_else(age_int %ni% c("0-14", "15-64", "total"), "65+", age_int),
           country = countrycode,
           sex = if_else(sex %in% c("f"), "Female", if_else(sex %in% c("m"), "Male", "b"))) %>%
    filter(age %ni% c("total", "0-14"), between(year, 2016, 2020), sex != "b") %>%
    group_by(country, year, week, age) %>%
    summarize(deaths15 = sum(death_count, na.rm = T))
## `summarise()` has grouped output by 'country', 'year'. You can override using the `.groups` argument.
  #STMF currently reports the UK estimate for England and Wales, Scotland, and Northern Ireland separately; we combine them into one country and use that estimate for the UK
  #Seeing if we need to adjust the UK estimate: we see if we have more than one containing the code GBR
  adjustUK <- if_else(length(grep("GBR", levels(as.factor(adj.total$country)))) > 1, T, F)
  
  #Print whether we need to adjust this
  print(paste("UK estimate being constructed from", length(grep("GBR", levels(as.factor(adj.total$country)))), "entities"))

  
  if (adjustUK <- T) {
    #England and Wales, Scotland, and NI may go up to different number of weeks. 
    #Make sure we have the same number of weeks for each
     week_final_uk <-  adj.total %>% 
       filter(grepl("GBR", country), year == 2020) %>%
       ungroup() %>%
       group_by(country) %>%
       summarize(max_week = max(week), .groups = "keep") %>%
       ungroup() %>%
       summarize(min_week = min(max_week)) %>%
       pull(min_week)
    
    #Now construct a single estimate for the UK
    adj.total.uk <- adj.total %>% 
      filter(grepl("GBR", country) & week <= week_final_uk) %>%
      ungroup() %>%
      group_by(year, week, age) %>%
      summarize(deaths15 = sum(deaths15), .groups = "keep") %>% #Adding up UK estimates
      mutate(country = "GBR") #Creating one country code
    
    adj.total2 <- adj.total %>% 
      filter(!grepl("GBR", country)) %>% #Combining them with all other countries in the dataset
      bind_rows(adj.total.uk)
  } else {
    adj.total2 <- adj.total
  }
    
  final_week <- 24
  
  #Now convert weekly data into monthly data
    adj.monthly <- adj.total2 %>%
      filter(week <= final_week) %>% #removing all data after a set cutoff point for comparability between countries
      mutate(month = as.numeric(as.factor(cut(week, breaks = seq(1, final_week+1, by = 4), 
                                              right = FALSE)))) %>%
      ungroup() %>%
      filter(month %in% c(3,4,5,6)) %>%
      group_by(country, year, age) %>%
      summarize(deaths15 = sum(deaths15), .groups = "keep") %>% #generating monthly death counts and exposures
      mutate(period = if_else(year %in% c(2016:2019), "Past", "Current"))
    
  #Making sure this worked
  print(paste("UK estimates still need adjusting: ", if_else(length(grep("GBR", levels(as.factor(adj.monthly$country)))) > 1, T, F)))

 #Now we can generate excess mortality

  adj.past <- adj.monthly %>%  #Calculate average for past 4-year period
    filter(period == "Past") %>%
    ungroup() %>%
    group_by(country, age) %>%
    summarize(mean_past_deaths15 = mean(deaths15))

   adj.current <- adj.monthly %>% filter(period == "Current") %>% #Find current mx values
    ungroup() %>%
    mutate(current_deaths15 = deaths15) %>% 
              dplyr::select(-c(year, deaths15))
  
    #Getting final monthly factors
    adj.monthly.final <- left_join(adj.past, adj.current, #Combine past and current values
                                by = c("country" = "country", "age" = "age")) %>%
      filter(country %ni% c("TWN")) %>% #Removing Taiwan for now
    mutate(mean_past_deaths15 = if_else(mean_past_deaths15 == 0, 10^-6, mean_past_deaths15),
          stmf_em15 = 100*(current_deaths15 - mean_past_deaths15)/mean_past_deaths15,
           country_name =  countrycode(substr(country, 1, 3), origin = "iso3c", destination = "un.name.en"),
           country_name =gsub("United Kingdom of Great Britain and Northern Ireland",
                                      "United Kingdom", country_name))
```


### Figure A: Death rates by country

```{r}
em.model <- by(em, em$age_interval, function(x) lm(em ~ 0 + country, data = x, na.action = na.omit))

model.output <- lapply(1:length(em.model), function(x) {
  em.model[[x]] %>%
    tidy %>%
    mutate(group = unique(em$age_interval)[x])
})

em.model.age <- bind_rows(model.output) %>%
  mutate(country = gsub("country", "", term),
         country = gsub("_", " ", country))

em.model.both <- full_join(em.model.age %>% filter(group != "0-14"), adj.monthly.final, by = c("country" = "country_name", "group" = "age")) %>%
  mutate(country = if_else(country == "United States of America", "USA", country))

#Get the order of countries for later
country.reorder.em <- em.model.age %>%
  filter(group == "65+") %>%
  mutate(country = if_else(country == "United States of America", "USA", country)) %>%
  arrange(estimate) %>%
  pull(country)

#Get top quartile of countries by mortality
country.75.quartile.em <- em.model.age %>%
  filter(group == "65+") %>%
  filter(estimate >= quantile(estimate, 0.75)) %>%
  arrange(estimate) %>%
  pull(country)

country.25.quartile.em <- em.model.age %>%
  filter(group == "65+") %>%
  filter(estimate <= quantile(estimate, 0.25)) %>%
  arrange(estimate) %>%
  pull(country)
  
```

Note: I tried adding in the 0-14 rates, but they are too noisy to include. 

```{r, fig.height = 6}
#Means by age
em.model.both %>%
  ggplot(aes(x = factor(country, levels = country.reorder.em), y=estimate, ymin=estimate - qnorm(0.95)*std.error, ymax=estimate + qnorm(0.95)*std.error, color = group, group = group)) +
  geom_hline(yintercept=0, linetype="11", colour="grey60") +
    geom_errorbar(width=0.1, position = position_dodge(0.8)) + 
  geom_point(aes(shape = "Simulation Output"), position = position_dodge(0.8)) +
  geom_point(aes(y = stmf_em15, shape = "STMF Data"), position = position_dodge(0.8)) +
  geom_vline(xintercept=country.75.quartile.em[1], 
             linetype="11", colour="black") +
     geom_vline(xintercept=country.25.quartile.em[length(country.25.quartile.em)],  linetype="11", colour="black") +
  geom_text(aes(x = country.75.quartile.em[1], y = 40, 
                label = "75th quartile"), color = "black", vjust = 0.1, size = 3) +
  geom_text(aes(x = country.25.quartile.em[length(country.25.quartile.em)], y = 40, 
                label = "25th quartile"), color = "black", vjust = 0.1, size = 3) +
  coord_flip() +
  labs(y = "Excess Mortality (%)", 
       title = "Excess Mortality by Country", x = "Country", color = "Age", shape = "Source") +
  theme(axis.text.x = element_text(size=20),
        title = element_text(size=20))+
  theme_bw()

ggsave("~/covid_simulation/Output/paa_graphs/em_bycountry.png")

```
```{r}
#Means by age
em.model.both %>%
  filter(country %in% c("Sweden", "Denmark", "USA", "Spain", "Italy", "Germany", "Canada", "Croatia")) %>%
  ggplot(aes(x = factor(country, levels = country.reorder.em), y=estimate, ymin=estimate - qnorm(0.95)*std.error, ymax=estimate + qnorm(0.95)*std.error, color = group, group = group)) +
  geom_hline(yintercept=0, linetype="11", colour="grey60") +
    geom_errorbar(width=0.1, position = position_dodge(0.8)) + 
  geom_point(aes(shape = "Simulation Output"), position = position_dodge(0.8)) +
  geom_point(aes(y = stmf_em15, shape = "STMF Data"), position = position_dodge(0.8)) +
  coord_flip() +
  labs(y = "Excess Mortality (%)", 
       title = "Excess Mortality by Country (Selected List)", x = "Country", color = "Age", shape = "Source") +
  theme(axis.text.x = element_text(size=20),
        title = element_text(size=20))+
  theme_bw()

ggsave("~/covid_simulation/Output/paa_graphs/em_bycountry_selected.png")

```


```{r}
#Correlation coefficient
cor(em.model.both$estimate, em.model.both$stmf_em15)


```

### Figure B: Age Structure Variation within Our Data

```{r}
oadr <- age_str %>%
  filter(age == "65+") %>%
  group_by(index, sim.id_covid, sim.id_other, country) %>%
  summarize(n_den = sum(n_den),
            total_15 = sum(total_15)) %>%
  mutate(oadr = n_den/total_15) %>%
  group_by(country) %>%
  summarize(oadr = mean(oadr)) %>%
  arrange(-oadr)
  
oadr.countries <- oadr %>% pull(country)

oadr.highest <- oadr.countries[1]
oadr.lowest <- oadr.countries[length(oadr.countries)]
oadr.highest.val <- oadr$oadr[1]
oadr.lowest.val <- oadr$oadr[length(oadr.countries)]

oadr.75 <- oadr %>% filter(oadr >= quantile(oadr, .75)) %>% pull(country)
oadr.25 <- oadr %>% filter(oadr <= quantile(oadr, .25)) %>% pull(country)
```

```{r}
estMeans_age_str_compare <- function(sex.val){
data.high <- age_str %>%
  filter(sex == sex.val, country %in% oadr.highest)

model.high <- lm(pc_age ~ 0 + age, data = data.high, na.action = na.omit)

res.high <- model.high %>%
  tidy %>%
  mutate(country = oadr.highest,
         oadr = 100*oadr.highest.val)

data.low <- age_str %>%
  filter(sex == sex.val, country %in% oadr.lowest)

model.low <- lm(pc_age ~ 0 + age, data = data.low, na.action = na.omit)

res.low <- model.low %>%
  tidy %>%
  mutate(country = oadr.lowest,
         oadr = 100*oadr.lowest.val)

res <- bind_rows(res.high, res.low)
res <- res %>%
  mutate(sex = sex.val)
return(res)
}
```

```{r}
age_str_compare <- bind_rows(lapply(c("M", "F"), function(x) estMeans_age_str_compare(sex.val = x))) %>% 
  mutate(age = gsub("age", "", term))
```

```{r}
age_str_compare %>%
  mutate(estimate = if_else(sex == "M", -estimate, estimate),
         #std.error = if_else(sex == "M", -std.error, std.error),
         sex = if_else(sex == "M", "Male", "Female"),
         country.val = paste0(country, "(", round(oadr,1), ")")) %>%
ggplot(aes(x = age, y = estimate, alpha = country.val,
           fill = sex)) + 
  geom_bar(data = . %>% filter(sex == "Female"), stat = "identity",
           position = position_dodge()) + 
  geom_bar(data = . %>% filter(sex == "Male"), stat = "identity",
           position = position_dodge()) +
  scale_y_continuous(breaks = seq(-100, 100, 25),
                     labels = as.character(c(seq(100, 25, -25), seq(0, 100, 25)))) +
  coord_flip() + 
  theme_bw() +
  labs(x = "Age", y = "% of Population", fill = "Sex", 
       title = "Variability of Age Structure", alpha = "Country")
```

Alternative version comparing quantiles (the version we use)

```{r}
estMeans_age_str_quantile <- function(sex.val){
data.high <- age_str %>%
  filter(sex == sex.val, country %in% oadr.75)

model.high <- lm(pc_age ~ 0 + age, data = data.high, na.action = na.omit)

res.high <- model.high %>%
  tidy %>%
  mutate(quantile = "75th")

data.low <- age_str %>%
  filter(sex == sex.val, country %in% oadr.25)

model.low <- lm(pc_age ~ 0 + age, data = data.low, na.action = na.omit)

res.low <- model.low %>%
  tidy %>%
  mutate(quantile = "25th")

res <- bind_rows(res.high, res.low)
res <- res %>%
  mutate(sex = sex.val)
return(res)
}
```

```{r}
age_str_quantile <- bind_rows(lapply(c("M", "F"), function(x) estMeans_age_str_quantile(sex.val = x))) %>% 
  mutate(age = gsub("age", "", term))
```

```{r}
age_str_quantile %>%
  mutate(estimate = if_else(sex == "M", -estimate, estimate),
         #std.error = if_else(sex == "M", -std.error, std.error),
         sex = if_else(sex == "M", "Male", "Female")) %>%
ggplot(aes(x = age, y = estimate, alpha = quantile,
           fill = sex, 
           ymin=estimate - qnorm(0.95)*std.error, ymax=estimate + qnorm(0.95)*std.error)) + 
  geom_bar(data = . %>% filter(sex == "Female"), stat = "identity",
           position = position_dodge()) + 
  geom_bar(data = . %>% filter(sex == "Male"), stat = "identity",
           position = position_dodge()) +
   geom_errorbar(data = . %>% filter(sex == "Male"), width = 0.5,
                 position = position_dodge()) +
    geom_errorbar(data = . %>% filter(sex == "Female"), width = 0.5,
                  position = position_dodge()) +
  scale_y_continuous(breaks = seq(-100, 100, 25),
                     labels = as.character(c(seq(100, 25, -25), seq(0, 100, 25)))) +
  coord_flip() + 
  theme_bw() +
  labs(x = "Age", y = "% of Population", fill = "Sex", 
       title = "Variability of Age Structure", alpha = "OADR Quantile")

ggsave("~/covid_simulation/Output/paa_graphs/age_str_quantile_oadr.png")
```

### Figure C: Kin Availability by Age

```{r}
estMeans_avail_kintype_quartiles <- function(sex.val, kintype.val, group.val){
kin_avail <- kin_ebr %>%
  filter(sex == sex.val, kintype == kintype.val, 
         pc_withkin > 1, age == group.val) %>%
  group_by(country) %>%
  summarize(pc_withkin = mean(pc_withkin, na.rm = T)) %>%
  arrange(-pc_withkin)

country.75.quartile.avail <- kin_avail %>%
  filter(pc_withkin >= quantile(pc_withkin, .75)) %>%
  pull(country)

country.25.quartile.avail <- kin_avail %>%
  filter(pc_withkin <= quantile(pc_withkin, .25)) %>%
  pull(country)

data.75 <- kin_ebr %>%
  filter(sex == sex.val, pc_withkin > 1, kintype == kintype.val, country %in% country.75.quartile.avail)

model.75 <- lm(pc_withkin ~ 0 + age, data = data.75, na.action = na.omit)

res.75 <- model.75 %>%
  tidy %>%
  mutate(quartile = "75th")

data.25 <- kin_ebr %>%
  filter(sex == sex.val, pc_withkin > 1, kintype == kintype.val, country %in% country.25.quartile.avail)

model.25 <- lm(pc_withkin ~ 0 + age, data = data.25, na.action = na.omit)

res.25 <- model.25 %>%
  tidy %>%
  mutate(quartile = "25th")

res <- bind_rows(res.75, res.25)
res <- res %>%
  mutate(sex = sex.val, kintype.val = kintype.val)
return(res)
}
```

```{r}
gparents <- bind_rows(lapply(c("M", "F"), function(x) estMeans_avail_kintype_quartiles(kintype.val = "gparents", sex.val = x, group.val = "30-44")))
parents <- bind_rows(lapply(c("M", "F"), function(x) estMeans_avail_kintype_quartiles(kintype.val = "parents", sex.val = x, group.val = "30-44")))
siblings <- bind_rows(lapply(c("M", "F"), function(x) estMeans_avail_kintype_quartiles(kintype.val = "siblings", sex.val = x, group.val = "30-44")))
children <- bind_rows(lapply(c("M", "F"), function(x) estMeans_avail_kintype_quartiles(kintype.val = "children", sex.val = x, group.val = "30-44")))
nuclear <- bind_rows(lapply(c("M", "F"), function(x) estMeans_avail_kintype_quartiles(kintype.val = "nuclear", sex.val = x, group.val = "30-44")))
spouse <- bind_rows(lapply(c("M", "F"), function(x) estMeans_avail_kintype_quartiles(kintype.val = "spouse", sex.val = x, group.val = "30-44")))

all_means_avail_quartiles <- bind_rows(gparents, parents, spouse, siblings, children, nuclear) %>%
  mutate(age = gsub("age", "", term),
         kintype = kintype.val,
         kintype = str_to_title(if_else(kintype == "gparents", "grandparents", kintype)),
         kintype = ordered(kintype, levels = c("Grandparents", "Parents", "Spouse", "Siblings", "Children", "Nuclear")))
```


```{r, fig.height = 6}
all_means_avail_quartiles %>%
  mutate(estimate = if_else(sex == "M", -estimate, estimate),
         std.error = if_else(sex == "M", -std.error, std.error),
         sex = if_else(sex == "M", "Male", "Female")) %>%
ggplot(aes(x = age, y = estimate, fill = sex,
           ymin=estimate - qnorm(0.95)*std.error, 
           ymax=estimate + qnorm(0.95)*std.error, alpha = quartile)) + 
  geom_bar(data = . %>% filter(sex == "Female"), stat = "identity",
           position = position_dodge()) + 
  geom_bar(data = . %>% filter(sex == "Male"), stat = "identity",
           position = position_dodge()) +
   geom_errorbar(data = . %>% filter(sex == "Male"), width = 0.5,
                 position = position_dodge()) +
    geom_errorbar(data = . %>% filter(sex == "Female"), width = 0.5,
                  position = position_dodge()) +
  scale_y_continuous(breaks = seq(-100, 100, 25),
                     labels = as.character(c(seq(100, 25, -25), seq(0, 100, 25)))) +
  coord_flip() + 
  theme_bw() +
  facet_wrap(~kintype, ncol = 2) +
  labs(x = "Age", y = "% with at least one relative in Feb 2020", 
       fill = "Sex", alpha = "Quartile",
       title = "Variation in Kin Availability by Age and Sex")

ggsave("~/covid_simulation/Output/paa_graphs/kin_avail_quartiles_compare.png")
```

### Figure D: Kin Loss by Age and Sex

```{r}
countries.kinloss <- c("United States of America", "Spain", "Sweden", "Denmark", "Norway") #Countries we're interested in
```

```{r}
estMeans_probloss_country <- function(kintype.val, sex.val){
data <- kin_ebr %>%
  filter(kintype == kintype.val, sex == sex.val, pc_withkin > 1)

model <- by(data, data[, "age"], function(y) lm(probloss_abs_diff_adj ~ 0 + country, 
                                                data = y, na.action = na.omit))

res <- bind_rows(lapply(1:length(names(model)), function(z) {
  model[[names(model[z])]] %>%
  tidy %>%
  mutate(group = names(model[z]))
}))

res <- res %>%
  mutate(sex = sex.val, kintype = kintype.val)
return(res)
}

estMeans_no14_probloss_country <- function(kintype.val, sex.val){
data <- kin_ebr %>%
  filter(kintype == kintype.val, sex == sex.val, pc_withkin > 1, age!= "0-14")

model <- by(data, data[, "age"], function(y) lm(probloss_abs_diff_adj ~ 0 + country, 
                                                data = y, na.action = na.omit))

res <- bind_rows(lapply(1:length(names(model)), function(z) {
  model[[names(model[z])]] %>%
  tidy %>%
  mutate(group = names(model[z]))
}))

res <- res %>%
  mutate(sex = sex.val, kintype = kintype.val)
return(res)
}

estMeans_no29_probloss_country <- function(kintype.val, sex.val){
data <- kin_ebr %>%
  filter(kintype == kintype.val, sex == sex.val, pc_withkin > 1, age %ni% c("0-14","15-29"))

model <- by(data, data[, "age"], function(y) lm(probloss_abs_diff_adj ~ 0 + country, 
                                                data = y, na.action = na.omit))

res <- bind_rows(lapply(1:length(names(model)), function(z) {
  model[[names(model[z])]] %>%
  tidy %>%
  mutate(group = names(model[z]))
}))

res <- res %>%
  mutate(sex = sex.val, kintype = kintype.val)
return(res)
}
```

```{r}  
gparents <- bind_rows(lapply(c("M", "F"), 
                             function(x) estMeans_probloss_country(kintype.val = "gparents", sex.val = x)))
parents <- bind_rows(lapply(c("M", "F"), function(x) estMeans_probloss_country(kintype.val = "parents", sex.val = x)))
siblings <- bind_rows(lapply(c("M", "F"), function(x) estMeans_probloss_country(kintype.val = "siblings", sex.val = x)))
children <- bind_rows(lapply(c("M", "F"), function(x) estMeans_no14_probloss_country(kintype.val = "children", sex.val = x)))
nuclear <- bind_rows(lapply(c("M", "F"), function(x) estMeans_probloss_country(kintype.val = "nuclear", sex.val = x)))
spouse <- bind_rows(lapply(c("M", "F"), function(x) estMeans_no29_probloss_country(kintype.val = "spouse", sex.val = x)))

all_means_probloss_country <- bind_rows(gparents, parents, spouse, siblings, children, nuclear) %>%
  mutate(country = gsub("country", "", term),
         country = gsub("_", " ", country),
         age = group,
         kintype = str_to_title(if_else(kintype == "gparents", "grandparents", kintype)),
                   kintype = ordered(kintype, levels = c("Grandparents", "Parents", "Spouse", "Siblings", "Children", "Nuclear"))) %>%
  filter(country %in% c(countries.kinloss))
```

```{r}
kin_ebr_old <- kin_ebr #Preserve old dataset
```

```{r}
kin_ebr <- kin_ebr %>%
  mutate(country = if_else(country %in% country.75.quartile.em, "75th",
                   if_else(country %in% country.25.quartile.em, "25th",
                    NA_character_))) %>%
  filter(!is.na(country))

gparents <- bind_rows(lapply(c("M", "F"), function(x) estMeans_probloss_country(kintype.val = "gparents", sex.val = x)))
parents <- bind_rows(lapply(c("M", "F"), function(x) estMeans_probloss_country(kintype.val = "parents", sex.val = x)))
siblings <- bind_rows(lapply(c("M", "F"), function(x) estMeans_probloss_country(kintype.val = "siblings", sex.val = x)))
children <- bind_rows(lapply(c("M", "F"), function(x) estMeans_no14_probloss_country(kintype.val = "children", sex.val = x)))
nuclear <- bind_rows(lapply(c("M", "F"), function(x) estMeans_probloss_country(kintype.val = "nuclear", sex.val = x)))
spouse <- bind_rows(lapply(c("M", "F"), function(x) estMeans_no29_probloss_country(kintype.val = "spouse", sex.val = x)))

all_means_quartile <- bind_rows(gparents, parents, spouse, siblings, children, nuclear) %>%
  mutate(country = gsub("country", "", term), 
         country = paste(country, "Quartile"),
         age = group,
         kintype = str_to_title(if_else(kintype == "gparents", "grandparents", kintype)),
                   kintype = ordered(kintype, levels = c("Grandparents", "Parents", "Spouse", "Siblings", "Children", "Nuclear")))

kin_ebr <- kin_ebr_old
```

```{r}
#combine datasets
probloss_compare <- bind_rows(all_means_probloss_country, all_means_quartile)
```


```{r, fig.height = 6.5}
probloss_compare %>%
  mutate(estimate = if_else(sex == "M", -estimate, estimate),
         std.error = if_else(sex == "M", -std.error, std.error),
         sex = if_else(sex == "M", "Male", "Female"),
         country = if_else(country == "United States of America", "USA", country)) %>%
ggplot(aes(x = age, y = estimate, fill = sex,
           ymin=estimate - qnorm(0.95)*std.error, 
           ymax=estimate + qnorm(0.95)*std.error)) + 
  geom_bar(data = . %>% filter(sex == "Female"), stat = "identity") + 
  geom_bar(data = . %>% filter(sex == "Male"), stat = "identity") +
  geom_errorbar(data = . %>% filter(sex == "Male"), width = 0.5, 
                position = position_dodge()) +
    geom_errorbar(data = . %>% filter(sex == "Female"), width = 0.5,
                  position = position_dodge()) +
    scale_y_continuous(breaks = seq(-1, 1, 0.5),
    labels = as.character(c(seq(1, 0.5, -.5), seq(0, 1, 0.5)))) +
  coord_flip() + 
  theme_bw() +
  facet_grid(rows = vars(kintype), cols = vars(country)) +
  labs(x = "Age", y = "% point difference for all individuals", fill = "Sex", 
       title = "Excess Probability of Kin Loss by Age and Sex")

ggsave("~/covid_simulation/Output/paa_graphs/kin_probloss_quartiles_compare.png")
```

```{r}
probloss_compare %>%
  mutate(estimate = if_else(sex == "M", -estimate, estimate),
         std.error = if_else(sex == "M", -std.error, std.error),
         sex = if_else(sex == "M", "Male", "Female"),
         country = if_else(country == "United States of America", "USA", country)) %>%
  filter(country %in% c("Sweden", "Denmark", "USA", "Spain"), 
         kintype %ni% c("Nuclear")) %>%
ggplot(aes(x = age, y = estimate, fill = sex,
           ymin=estimate - qnorm(0.95)*std.error, 
           ymax=estimate + qnorm(0.95)*std.error)) + 
  geom_bar(data = . %>% filter(sex == "Female"), stat = "identity") + 
  geom_bar(data = . %>% filter(sex == "Male"), stat = "identity") +
  geom_errorbar(data = . %>% filter(sex == "Male"), width = 0.5, 
                position = position_dodge()) +
    geom_errorbar(data = . %>% filter(sex == "Female"), width = 0.5,
                  position = position_dodge()) +
    scale_y_continuous(breaks = seq(-1, 1, 0.5),
    labels = as.character(c(seq(1, 0.5, -.5), seq(0, 1, 0.5)))) +
  coord_flip() + 
  theme_bw() +
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=13),
        text=element_text(size=10)) +
  facet_grid(rows = vars(kintype), cols = vars(country)) +
  labs(x = "Age", y = "% point difference for all individuals", fill = "Sex",
       title = "Estimates of Excess Bereavement for Selected Countries")

ggsave("~/covid_simulation/Output/paa_graphs/kin_probloss_iussp_filtered.png")
```


```{r}
probloss_compare %>%
  mutate(estimate = if_else(sex == "M", -estimate, estimate),
         std.error = if_else(sex == "M", -std.error, std.error),
         sex = if_else(sex == "M", "Male", "Female"),
         country = if_else(country == "United States of America", "USA", country)) %>%
  filter(country %in% c("USA"), 
         kintype %ni% c("Spouse", "Nuclear")) %>%
ggplot(aes(x = age, y = estimate, fill = sex,
           ymin=estimate - qnorm(0.95)*std.error, 
           ymax=estimate + qnorm(0.95)*std.error)) + 
  geom_bar(data = . %>% filter(sex == "Female"), stat = "identity") + 
  geom_bar(data = . %>% filter(sex == "Male"), stat = "identity") +
  geom_errorbar(data = . %>% filter(sex == "Male"), width = 0.5, 
                position = position_dodge()) +
    geom_errorbar(data = . %>% filter(sex == "Female"), width = 0.5,
                  position = position_dodge()) +
    scale_y_continuous(breaks = seq(-1, 1, 0.5),
    labels = as.character(c(seq(1, 0.5, -.5), seq(0, 1, 0.5)))) +
  coord_flip() + 
  theme_bw() +
    theme(axis.text=element_text(size=10),
        axis.title=element_text(size=13),
        text=element_text(size=10)) +
  facet_grid(rows = vars(kintype), cols = vars(country)) +
  labs(x = "Age", y = "% point difference for all individuals", fill = "Sex")

ggsave("~/covid_simulation/Output/paa_graphs/kin_probloss_usa_filtered.png")
```


```{r}
probloss_compare %>%
  mutate(estimate = if_else(sex == "M", -estimate, estimate),
         std.error = if_else(sex == "M", -std.error, std.error),
         sex = if_else(sex == "M", "Male", "Female"),
         country = if_else(country == "United States of America", "USA", country), 
         country = if_else(country == "25th Quartile", "25th Quartile (Negative)", country),
         country = if_else(country == "75th Quartile", "75th Quartile (Positive)", country)) %>%
  filter(country %in% c("75th Quartile (Positive)", "25th Quartile (Negative)"),
         kintype %ni% c("Spouse", "Nuclear")) %>%
ggplot(aes(x = age, y = estimate, fill = sex,
           ymin=estimate - qnorm(0.95)*std.error, 
           ymax=estimate + qnorm(0.95)*std.error)) + 
  geom_bar(data = . %>% filter(sex == "Female"), stat = "identity") + 
  geom_bar(data = . %>% filter(sex == "Male"), stat = "identity") +
  geom_errorbar(data = . %>% filter(sex == "Male"), width = 0.5, 
                position = position_dodge()) +
    geom_errorbar(data = . %>% filter(sex == "Female"), width = 0.5,
                  position = position_dodge()) +
    scale_y_continuous(breaks = seq(-1, 1, 0.5),
    labels = as.character(c(seq(1, 0.5, -.5), seq(0, 1, 0.5)))) +
  coord_flip() + 
  theme_bw() +
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=13),
        text=element_text(size=10)) +
  facet_grid(rows = vars(kintype), cols = vars(country)) +
  labs(x = "Age", y = "% point difference for all individuals", fill = "Sex")

ggsave("~/covid_simulation/Output/paa_graphs/kin_probloss_quartiles_only_filtered.png")
```


### Appendix Figures: Kin Loss by Country, Age, and Sex

```{r}
estMeans_probloss_country <- function(kintype.val, sex.val){
data <- kin_ebr %>%
  filter(kintype == kintype.val, sex == sex.val, pc_withkin > 1)

model <- by(data, data[, "age"], function(y) lm(probloss_abs_diff_adj ~ 0 + country, 
                                                data = y, na.action = na.omit))

res <- bind_rows(lapply(1:length(names(model)), function(z) {
  model[[names(model[z])]] %>%
  tidy %>%
  mutate(group = names(model[z]))
}))

res <- res %>%
  mutate(sex = sex.val, kintype = kintype.val)
return(res)
}

estMeans_no14_probloss_country <- function(kintype.val, sex.val){
data <- kin_ebr %>%
  filter(kintype == kintype.val, sex == sex.val, pc_withkin > 1, age!= "0-14")

model <- by(data, data[, "age"], function(y) lm(probloss_abs_diff_adj ~ 0 + country, 
                                                data = y, na.action = na.omit))

res <- bind_rows(lapply(1:length(names(model)), function(z) {
  model[[names(model[z])]] %>%
  tidy %>%
  mutate(group = names(model[z]))
}))

res <- res %>%
  mutate(sex = sex.val, kintype = kintype.val)
return(res)
}

estMeans_no29_probloss_country <- function(kintype.val, sex.val){
data <- kin_ebr %>%
  filter(kintype == kintype.val, sex == sex.val, pc_withkin > 1, age %ni% c("0-14","15-29"))

model <- by(data, data[, "age"], function(y) lm(probloss_abs_diff_adj ~ 0 + country, 
                                                data = y, na.action = na.omit))

res <- bind_rows(lapply(1:length(names(model)), function(z) {
  model[[names(model[z])]] %>%
  tidy %>%
  mutate(group = names(model[z]))
}))

res <- res %>%
  mutate(sex = sex.val, kintype = kintype.val)
return(res)
}
```

```{r}  
gparents <- bind_rows(lapply(c("M", "F"), 
                             function(x) estMeans_probloss_country(kintype.val = "gparents", sex.val = x)))
parents <- bind_rows(lapply(c("M", "F"), function(x) estMeans_probloss_country(kintype.val = "parents", sex.val = x)))
siblings <- bind_rows(lapply(c("M", "F"), function(x) estMeans_probloss_country(kintype.val = "siblings", sex.val = x)))
children <- bind_rows(lapply(c("M", "F"), function(x) estMeans_no14_probloss_country(kintype.val = "children", sex.val = x)))
nuclear <- bind_rows(lapply(c("M", "F"), function(x) estMeans_probloss_country(kintype.val = "nuclear", sex.val = x)))
spouse <- bind_rows(lapply(c("M", "F"), function(x) estMeans_no29_probloss_country(kintype.val = "spouse", sex.val = x)))

all_means_probloss_country <- bind_rows(gparents, parents, spouse, siblings, children, nuclear) %>%
  mutate(country = gsub("country", "", term),
         country = gsub("_", " ", country))
```

```{r}
makeLossGraph <- function(kintype.val, data) {
data %>%
  filter(kintype == kintype.val) %>%
  ggplot(aes(factor(country, levels = country.reorder.em), y=estimate, ymin=estimate - qnorm(0.95)*std.error, ymax=estimate + qnorm(0.95)*std.error, 
             color = group, group = group, shape = sex)) +
  geom_hline(yintercept=0, linetype="11", colour="grey60") +
  geom_errorbar(width=0.1) + #, position = position_dodge(0.8) 
    #Dodging makes the graph messier
  geom_point() + #position = position_dodge(0.8)
  coord_flip() +
  labs(y = "% point difference for all individuals", x = "Country", title = paste0("Probability of Loss (", str_to_title(if_else(kintype.val == "gparents", "grandparents", kintype.val)), ")"), color = "Age", shape = "Sex") +
  theme_bw()
  #+ scale_color_viridis_d() #Find better color scheme
}
```

```{r}
lapply(unique(kin_ebr$kintype), function(x) makeLossGraph(kintype.val = x, data = all_means_probloss_country))
```
