---
title: "Results for Paper"
output:
  html_document:
    df_print: paged
---

## Data Preparation

```{r message=FALSE}
#Load functions
#Source functions and packages
source("~/covid_simulation/Kin_death/01_load_functions.R")
source('~/covid_simulation/Kin_death/functions_bereavement.R')

#Require this additional packages
require(broom)
require(countrycode)
require(ggrepel)
require(viridis)
require(kableExtra)
require(ISOweek)
require(splitstackshape)
require(gridExtra)
require(ggh4x)

#Load data: currently, this points to the latest version with data for the first wave
data <- get(load(file = "~/covid_simulation/Data/finaldata_v2.RData"))
```

```{r}
#Find numbers for indices for each country
indices <- data$numbers %>%
  group_by(country) %>%
  summarize(max_index = min(nsims))
```

```{r}
#Burden of bereavement object
kin_ebr <-data$kin_bb %>%
  full_join(., indices, by = c("country" = "country")) %>%
  filter(!is.na(scenario)) %>% 
  mutate(sex = ifelse(grepl("f1", category), "F", "M"),
         age = gsub("f[0-1]{1}", "", category),
         category = NULL) %>%
  ungroup() %>%
  group_by(country, scenario, sex, age, kintype) %>%
  mutate(index = row_number(), category = NULL) %>%
  filter(index <= max_index) %>%
  ungroup() %>%
  pivot_wider(id_cols = c("country", "sex", "age", "kintype", "index"), 
              names_from = "scenario", 
              values_from = c("mean_post_all", "mean_pre_all", "mean_pre_with", "sd_pre_with", "n_withkin", 
                              "mean_post_with", "sd_post_with", "sim.id", "n_losekin", "n_total")) %>%
  mutate(bereavement_covid = (mean_pre_with_covid - mean_post_with_covid),
         bereavement_other = (mean_pre_with_other - mean_post_with_other),
         n_withkin = (n_withkin_covid + n_withkin_other)/2,
         n_total = (n_total_covid + n_total_other)/2,
         pc_withkin = (n_withkin/n_total)*100,
         probloss_covid = 100*(n_losekin_covid/n_withkin_covid),
         probloss_other = 100*(n_losekin_other/n_withkin_other),
         probloss_rel_diff = 100*(probloss_covid - probloss_other)/probloss_other,
         probloss_abs_diff = probloss_covid - probloss_other,
         probloss_abs_diff_adj = probloss_abs_diff*pc_withkin/100,
         probloss_rel_diff_adj = probloss_rel_diff*pc_withkin/100,
         probloss_other_adj = (probloss_other*(n_withkin_other/n_total_other))/100,
         ccode = countrycode(gsub("_", " ", country), 
                             origin = 'country.name', destination = 'iso3c'))
```

```{r}
# Kin ratio object
  kin_structure <- data$kin_ratio %>%
    full_join(., indices, by = c("country" = "country")) %>%
    filter(!is.na(scenario)) %>% 
    mutate(sex = ifelse(grepl("f1", category), "F", "M"),
           age = gsub("f[0-1]{1}", "", category),
           category = NULL) %>%
    ungroup() %>%
    group_by(country, scenario, sex, age, kintype) %>%
    mutate(index = row_number(), category = NULL) %>%
    filter(index <= max_index) %>%
    ungroup() %>%
    pivot_wider(id_cols = c("country", "sex", "age", "kintype", "index"), 
                names_from = "scenario", 
                values_from = c("count_all", "sd_all", "count_female", "count_male",
                                "count_65plus", "count_below65", "n_egos", "sim.id")) %>%
    mutate(ccode = countrycode(gsub("_", " ", country), 
                               origin = 'country.name', destination = 'iso3c'),
           count_all_diff = count_all_covid - count_all_other)
```

```{r}
#Death rates object
  death_rates <- data$death_rates %>%
  full_join(., indices, by = c("country" = "country")) %>%
  filter(!is.na(scenario)) %>% 
  mutate(sex = ifelse(fem == 1, "F", "M")) %>%
  ungroup() %>%
  group_by(country, scenario, sex, age) %>%
  mutate(index = row_number(), fem = NULL) %>%
  filter(index <= max_index) %>%
  ungroup() %>%
  pivot_wider(id_cols = c("country", "sex", "age", "index"), 
              names_from = "scenario", 
            values_from = c("n_num", "n_den", "value", "sim.id")) 
```

```{r}
  #Object used for excess mortality analysis
  em <- death_rates %>%
  filter(age %ni% c("all_sum", "all_mid")) %>%
  mutate(age_interval = if_else(age %in% c("0-14"), "0-14", 
         if_else(age %in% c("65+"), "65+", "15-64"))) %>%
  ungroup() %>%
  group_by(index, country, sim.id_covid, sim.id_other, age_interval) %>%
  summarize(n_num_covid = sum(n_num_covid, na.rm = T),
            n_num_other = sum(n_num_other, na.rm = T)) %>%
    mutate(em = 100*((n_num_covid - n_num_other)/n_num_other),
           em = if_else(em == Inf, NaN, em))
```

```{r}
  #Object used for age structure analysis
  age_str_indiv <- death_rates %>%
  filter(age %ni% c("all_sum", "all_mid")) %>%
  ungroup() %>%
  group_by(index, country, sim.id_covid, sim.id_other, age, sex) %>%
  summarize(n_den_covid = sum(n_den_covid, na.rm = T),
            n_den_other = sum(n_den_other, na.rm = T)) %>%
    mutate(n_den = (n_den_covid + n_den_other)/2)

age_str_total <- age_str_indiv %>%
  ungroup() %>%
  group_by(index, country, sim.id_covid, sim.id_other, sex) %>%
  summarize(total = sum(n_den))

age_str_15 <- age_str_indiv %>%
  ungroup() %>%
  filter(age %in% c("15-29", "30-44", "45-64")) %>%
  group_by(index, country, sim.id_covid, sim.id_other, sex) %>%
  summarize(total_15 = sum(n_den))

age_str <- merge(age_str_indiv, merge(age_str_total, age_str_15))


age_str <- age_str %>%
  mutate(pc_age = 100*(n_den/total))
```

```{r}
#Load data and calculate weekly deaths for counterfactual and Covid cases
stmf <- fread("~/covid_simulation/Rcode/stmf-mar9-run.csv", stringsAsFactors = F)
names(stmf) <- tolower(names(stmf)) #Make names lowercase

#Keeping only countries that have data for 2020
keepcountry <- unique(stmf$countrycode[which(stmf$year == 2020)])

#Pivoting the STMF data into long format
adj.total <- stmf %>%
  dplyr::select(-c(split, splitsex, forecast)) %>% #removing variables
  filter(countrycode %in% keepcountry) %>%
  pivot_longer(-c(year, week, countrycode, sex), 
               names_to = c("type", "age"), 
               values_to = "rate", names_sep = 1) %>% #pivoting
  pivot_wider(names_from = "type", values_from = "rate") %>%
  mutate(death_count = d, #renaming and generating new versions of variables
         death_rate = r,
         age = gsub("85p", "85-99", gsub("_", "-", age)),
          age_int = age,
        age = if_else(age_int %ni% c("0-14", "15-64", "total"), "65+", age_int),
         country = countrycode,
         sex = if_else(sex %in% c("f"), "Female", if_else(sex %in% c("m"), "Male", "b"))) %>%
  filter(age %ni% c("total", "0-14"), between(year, 2015, 2020), sex != "b") %>%
    group_by(country, year, week, age) %>%
    summarize(deaths15 = sum(death_count, na.rm = T))

#STMF currently reports the UK estimate for England and Wales, Scotland, and Northern Ireland separately; we combine them into one country and use that estimate for the UK
#Seeing if we need to adjust the UK estimate: we see if we have more than one containing the code GBR
adjustUK <- if_else(length(grep("GBR", levels(as.factor(adj.total$country)))) > 1, T, F)

#Print whether we need to adjust this
print(paste("UK estimate being constructed from", 
            length(grep("GBR", levels(as.factor(adj.total$country)))), "entities"))

if (adjustUK <- T) {
  #England and Wales, Scotland, and NI may go up to different number of weeks. 
  #Make sure we have the same number of weeks for each
  week_final_uk <-  adj.total %>% 
    filter(grepl("GBR", country), year == 2020) %>%
    ungroup() %>%
    group_by(country) %>%
    summarize(max_week = max(week), .groups = "keep") %>%
    ungroup() %>%
    summarize(min_week = min(max_week)) %>%
    pull(min_week)
  
  #Now construct a single estimate for the UK
  adj.total.uk <- adj.total %>% 
    filter(grepl("GBR", country) & week <= week_final_uk) %>%
    ungroup() %>%
    group_by(year, week, age) %>%
    summarize(deaths15 = sum(deaths15), .groups = "keep") %>% #Adding up UK estimates
    mutate(country = "GBR") #Creating one country code
  
  adj.total2 <- adj.total %>% 
    filter(!grepl("GBR", country)) %>% #Combining them with all other countries in the dataset
    bind_rows(adj.total.uk)
} else {
  adj.total2 <- adj.total
}

#Now convert weekly data into monthly, and calculate mx values
adj.monthly.pre <- adj.total2 %>%
  mutate(deaths15_daily = deaths15/7,
         days = 7) %>%
  ungroup() %>%
  group_by(country, age, year, week) %>%
  expandRows(count = "days") %>%
  mutate(day = row_number()) %>%
  ungroup() %>%
  mutate(date = paste0(year, "-W", str_pad(week, 2, pad = "0")
                       , "-", day),
         value = ISOweek2date(date),
         month = lubridate::month(value),
         stmf_year = year,
         year = lubridate::year(value)) %>%
  filter(year >= 2016 & year <= 2020, month %in% c(3,4,5,6))

#Some series only start in 2016, so 2016 January will be incomplete

adj.monthly <- adj.monthly.pre %>%
  group_by(country, year, age) %>%
  summarize(deaths15 = sum(deaths15_daily)) %>% 
  #generating monthly death counts and exposures
  mutate(period = if_else(year %in% c(2016:2019), "Past", "Current"))

#Making sure this worked
print(paste("UK estimates still need adjusting: ", 
            if_else(length(grep("GBR", levels(as.factor(adj.monthly$country)))) > 1, T, F)))

#Now we can generate mx values for the two periods
adj.past <- adj.monthly %>%  #Calculate average for past 4-year period
  filter(period == "Past") %>%
  ungroup() %>%
  group_by(country, age) %>%
  summarize(mean_past_deaths15 = mean(deaths15))

adj.current <- adj.monthly %>% filter(period == "Current") %>% #Find current mx values
  ungroup() %>%
  mutate(current_deaths15 = deaths15) %>% 
  dplyr::select(-c(year, deaths15))

#Getting final monthly mx values
    #Getting final monthly factors
    adj.monthly.final <- left_join(adj.past, adj.current, #Combine past and current values
                                by = c("country" = "country", "age" = "age")) %>%
      filter(country %ni% c("TWN")) %>% #Removing Taiwan for now
    mutate(mean_past_deaths15 = if_else(mean_past_deaths15 == 0, 10^-6, mean_past_deaths15),
          stmf_em15 = 100*(current_deaths15 - mean_past_deaths15)/mean_past_deaths15,
           country_name =  countrycode(substr(country, 1, 3), origin = "iso3c", destination = "un.name.en"),
           country_name =gsub("United Kingdom of Great Britain and Northern Ireland",
                                      "United Kingdom", country_name))
```


### Death rates by country

```{r}
em.model <- by(em, em$age_interval, function(x) 
  lm(em ~ 0 + country, data = x, na.action = na.omit))

model.output <- lapply(1:length(em.model), function(x) {
  em.model[[x]] %>%
    tidy %>%
    mutate(group = unique(em$age_interval)[x])
})

em.model.age <- bind_rows(model.output) %>%
  mutate(country = gsub("country", "", term),
         country = gsub("_", " ", country))
em.model.both <- full_join(em.model.age %>% filter(group != "0-14"), adj.monthly.final, by = c("country" = "country_name", "group" = "age")) %>%
  mutate(country = if_else(country == "United States of America", "USA", country))

#Get the order of countries for later
country.reorder.em <- em.model.age %>%
  filter(group == "65+") %>%
  mutate(country = if_else(country == "United States of America", "USA", country)) %>%
  arrange(estimate) %>%
  pull(country)
```

Note: I tried adding in the 0-14 rates, but they are too noisy to include. 

```{r, fig.height = 6}
#Means by age
em.model.both %>%
  ggplot(aes(x = factor(country, levels = country.reorder.em), y=estimate, ymin=estimate - qnorm(0.95)*std.error, ymax=estimate + qnorm(0.95)*std.error, color = group, group = group)) +
  geom_hline(yintercept=0, linetype="11", colour="grey60") +
    geom_errorbar(width=0.1, position = position_dodge(0.8)) + 
  geom_point(aes(shape = "Simulation Output"), position = position_dodge(0.8)) +
  geom_point(aes(y = stmf_em15, shape = "STMF Data"), position = position_dodge(0.8)) +
  coord_flip() +
  labs(y = "Excess Mortality (%)", 
       title = "Excess Mortality by Country", x = "Country", color = "Age", shape = "Source") +
  theme(axis.text.x = element_text(size=20),
        title = element_text(size=20))+
  theme_bw()

```

```{r}
#Correlation coefficient
cor.test(em.model.both$estimate[em.model.both$group == "65+"], 
    em.model.both$stmf_em15[em.model.both$group == "65+"])

cor.test(em.model.both$estimate[em.model.both$group == "15-64"], 
    em.model.both$stmf_em15[em.model.both$group == "15-64"])

cor.test(em.model.both$estimate, 
    em.model.both$stmf_em15)
```

```{r}
em.model.both %>%
  ggplot(aes(x = stmf_em15, y = estimate)) + geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~group) + 
  labs(x = "STMF Excess Mortality", y = "Excess Mortality from Simulations") +
  theme_bw()
  
```
```{r}
em.model.both <- full_join(em.model.age %>% filter(group != "0-14"), adj.monthly.final, by = c("country" = "country_name", "group" = "age")) %>%
  mutate(country = if_else(country == "United States of America", "USA", country))

#Get the order of countries for later
country.reorder.em <- em.model.age %>%
  filter(group == "65+") %>%
  mutate(country = if_else(country == "United States of America", "USA", country)) %>%
  arrange(estimate) %>%
  pull(country)
```


```{r}
diff_est <- em.model.both %>%
  filter(group == "65+") %>%
  mutate(diff = stmf_em15 - estimate,
         level = if_else(stmf_em15 >= 10, ">=10", 
                         if_else(between(stmf_em15, 0, 10), "0-10", "<0")))

countries.close <- diff_est %>%
    filter(abs(diff) <= 5) %>%
  arrange(level) %>%
  select(country, level)

#These are the countries where the estimate is within 5%
countries.close

```

Note: I tried adding in the 0-14 rates, but they are too noisy to include. 

### Age Structure Variation within Our Data

```{r}
oadr <- age_str %>%
  filter(age == "65+") %>%
  group_by(index, sim.id_covid, sim.id_other, country) %>%
  summarize(n_den = sum(n_den),
            total_15 = sum(total_15)) %>%
  mutate(oadr = n_den/total_15) %>%
  group_by(country) %>%
  summarize(oadr = mean(oadr)) %>%
  arrange(-oadr)
  
oadr.countries <- oadr %>% pull(country)

oadr.highest <- oadr.countries[1]
oadr.lowest <- oadr.countries[length(oadr.countries)]
oadr.highest.val <- oadr$oadr[1]
oadr.lowest.val <- oadr$oadr[length(oadr.countries)]

print(paste0("Highest OADR: ", oadr.highest, " (", round(oadr.highest.val, 2), ")"))
print(paste0("Lowest OADR: ", oadr.lowest, " (", round(oadr.lowest.val, 2), ")"))

#The data is somewhat right-skewed
oadr %>%
  ggplot() + geom_histogram(aes(x = oadr), binwidth = 0.05) +
  labs(x = "OADR") + 
  theme_bw()

```

### Kin Availability Variation within Our Data

```{r}
#Take a look at one of the major categories: grandparents for 30-44, averaged over sex 
#Looking at sexes individually does not change the order
gparents_avail <- kin_ebr %>%
  filter(sex == "F", kintype == "gparents", 
         pc_withkin > 1, age == "30-44") %>%
  group_by(country) %>%
  summarize(pc_withkin = mean(pc_withkin, na.rm = T)) %>%
  arrange(-pc_withkin)

gparents_avail %>%
  ggplot() + geom_histogram(aes(x = pc_withkin), binwidth = 1) +
  labs(x = "% 30-44 with a grandparent") + 
  theme_bw()
```

```{r}
#And siblings for 65+
siblings_avail <- kin_ebr %>%
  filter(kintype == "siblings", 
         pc_withkin > 1, age == "65+") %>%
  group_by(country) %>%
  summarize(pc_withkin = mean(pc_withkin, na.rm = T)) %>%
  arrange(-pc_withkin)

siblings_avail %>%
  ggplot() + geom_histogram(aes(x = pc_withkin), binwidth = 1) +
  labs(x = "% 65+ with a sibling") + 
  theme_bw()
```

### Main Result: Kin Loss by Age and Sex

```{r}
estMeans_probloss_country <- function(kintype.val, sex.val){
data <- kin_ebr %>%
  filter(kintype == kintype.val, sex == sex.val, pc_withkin > 1)

model <- by(data, data[, "age"], function(y) lm(probloss_abs_diff_adj ~ 0 + country, 
                                                data = y, na.action = na.omit))

res <- bind_rows(lapply(1:length(names(model)), function(z) {
  model[[names(model[z])]] %>%
  tidy %>%
  mutate(group = names(model[z]),
         type = "excess")
}))

model2 <- by(data, data[, "age"], function(y) lm(probloss_other_adj ~ 0 + country, 
                                                data = y, na.action = na.omit))

res2 <- bind_rows(lapply(1:length(names(model2)), function(z) {
  model2[[names(model2[z])]] %>%
  tidy %>%
  mutate(group = names(model2[z]),
         type = "counterfactual")
}))

res <- bind_rows(res, res2) %>%
  mutate(sex = sex.val, kintype = kintype.val)
return(res)
}

estMeans_no14_probloss_country <- function(kintype.val, sex.val){
data <- kin_ebr %>%
  filter(kintype == kintype.val, sex == sex.val, pc_withkin > 1, age!= "0-14")

model <- by(data, data[, "age"], function(y) lm(probloss_abs_diff_adj ~ 0 + country, 
                                                data = y, na.action = na.omit))

res <- bind_rows(lapply(1:length(names(model)), function(z) {
  model[[names(model[z])]] %>%
  tidy %>%
  mutate(group = names(model[z]),
         type = "excess")
}))

model2 <- by(data, data[, "age"], function(y) lm(probloss_other_adj ~ 0 + country, 
                                                data = y, na.action = na.omit))

res2 <- bind_rows(lapply(1:length(names(model2)), function(z) {
  model2[[names(model2[z])]] %>%
  tidy %>%
  mutate(group = names(model2[z]),
         type = "counterfactual")
}))

res <- bind_rows(res, res2) %>%
  mutate(sex = sex.val, kintype = kintype.val)
return(res)
}

estMeans_no29_probloss_country <- function(kintype.val, sex.val){
data <- kin_ebr %>%
  filter(kintype == kintype.val, sex == sex.val, pc_withkin > 1, age %ni% c("0-14","15-29"))

model <- by(data, data[, "age"], function(y) lm(probloss_abs_diff_adj ~ 0 + country, 
                                                data = y, na.action = na.omit))

res <- bind_rows(lapply(1:length(names(model)), function(z) {
  model[[names(model[z])]] %>%
  tidy %>%
  mutate(group = names(model[z]),
         type = "excess")
}))

model2 <- by(data, data[, "age"], function(y) lm(probloss_other_adj ~ 0 + country, 
                                                data = y, na.action = na.omit))

res2 <- bind_rows(lapply(1:length(names(model2)), function(z) {
  model2[[names(model2[z])]] %>%
  tidy %>%
  mutate(group = names(model2[z]),
         type = "counterfactual")
}))

res <- bind_rows(res, res2) %>%
  mutate(sex = sex.val, kintype = kintype.val)
return(res)}
```

```{r}  
gparents <- bind_rows(lapply(c("M", "F"), 
                             function(x) estMeans_probloss_country(kintype.val = "gparents", sex.val = x)))

parents <- bind_rows(lapply(c("M", "F"), function(x) estMeans_probloss_country(kintype.val = "parents", sex.val = x)))
siblings <- bind_rows(lapply(c("M", "F"), function(x) estMeans_probloss_country(kintype.val = "siblings", sex.val = x)))
children <- bind_rows(lapply(c("M", "F"), function(x) estMeans_no14_probloss_country(kintype.val = "children", sex.val = x)))
all <- bind_rows(lapply(c("M", "F"), function(x) estMeans_probloss_country(kintype.val = "all", sex.val = x)))
```

```{r}
probloss_compare <- bind_rows(gparents, parents, siblings, children) %>% #remove all
  mutate(country = gsub("country", "", term),
         country = gsub("_", " ", country),
         age = group,
         kintype = str_to_title(if_else(kintype == "gparents", "grandparents", kintype)),
                   kintype = ordered(kintype, levels = c("Grandparents", "Parents", "Siblings", "Children")),
         neg.val = if_else(estimate < 0, "*", NA_character_))
```

```{r}
#Code adapted from Diego's website
nudge_fun <- function(df){
  ifelse(df$sex == "Male", (df$estimate+5*df$std.error)*-1, df$estimate+3*df$std.error)
}
```


### Sweden and Norway Comparison Graph
```{r}
probloss_compare %>%
  mutate(estimate = if_else(sex == "M", -estimate, estimate),
         std.error = if_else(sex == "M", -std.error, std.error),
         sex = if_else(sex == "M", "Male", "Female"),
         country = if_else(country == "United States of America", "USA", country),
         type = ordered(type, levels = c("counterfactual", "excess")),
         type = str_to_title(type)) %>%
  filter(country %in% c("Sweden", "Norway")) %>%
ggplot(aes(x = age, y = estimate, fill = sex,
           ymin=estimate - qnorm(0.95)*std.error, 
           ymax=estimate + qnorm(0.95)*std.error)) + 
  geom_bar(data = . %>% filter(sex == "Female"), stat = "identity") + 
  geom_bar(data = . %>% filter(sex == "Male"), stat = "identity") +
  geom_errorbar(data = . %>% filter(sex == "Male"), width = 0.5, 
                position = position_dodge()) +
  geom_errorbar(data = . %>% filter(sex == "Female"), width = 0.5,
                  position = position_dodge()) +
    scale_y_continuous(breaks = seq(-1, 1, 0.5),
    labels = as.character(c(seq(1, 0.5, -.5), 
                            seq(0, 1, 0.5)))) +
  geom_text(aes(label = neg.val, y = 
                  if_else(sex == "Male", estimate - qnorm(0.95)*std.error+0.05,
                          estimate - qnorm(0.95)*std.error-0.05)), 
            size = 4) +
  coord_flip() + 
  theme_bw() +
  scale_fill_grey()+
  facet_nested(rows = vars(kintype), cols = vars(type, country)) +
  labs(x = "Age", y = "% point difference for all individuals", fill = "Sex", title = "Counterfactual and Excess Bereavement",
       subtitle = "Norway and Sweden, March-June 2020") +
  theme(legend.position = "bottom")

ggsave(filename = "~/covid_simulation/Output/paper_figures/compare_sweden_norway.png",
      height= 5.5, units = "in")
```

```{r}
#Pull the 65+ estimates from Sweden and Norway for use in the paper
paste("Sweden 65+ EM:", diff_est$stmf_em15[which(diff_est$country == "Sweden")])

paste("Norway 65+ EM:", diff_est$stmf_em15[which(diff_est$country == "Norway")])
```


```{r}
#Microsimulation-based estimate: 
paste("Sweden 65+ EM:", diff_est$estimate[which(diff_est$country == "Sweden")])

paste("Norway 65+ EM:", diff_est$estimate[which(diff_est$country == "Norway")])
```

## High and low mortality countries

```{r}
probloss_compare %>%
  mutate(estimate = if_else(sex == "M", -estimate, estimate),
         std.error = if_else(sex == "M", -std.error, std.error),
         sex = if_else(sex == "M", "Male", "Female"), 
         country = if_else(country=="United Kingdom", "UK", country),
         mort.level = if_else(country %in% 
                                c("Spain", "UK", "Italy", "Belgium"), "High Excess Mortality", 
                              if_else(country %in% 
                                        c("Australia", "Germany", "Portugal", "Iceland"), "Low and Medium Excess Mortality", NA_character_))) %>%
  filter(!is.na(mort.level),
         type == "excess") %>%
ggplot(aes(x = age, y = estimate, fill = sex,
           ymin=estimate - qnorm(0.95)*std.error, 
           ymax=estimate + qnorm(0.95)*std.error)) + 
  geom_bar(data = . %>% filter(sex == "Female"), stat = "identity") + 
  geom_bar(data = . %>% filter(sex == "Male"), stat = "identity") +
  geom_errorbar(data = . %>% filter(sex == "Male"), width = 0.5, 
                position = position_dodge()) +
    geom_errorbar(data = . %>% filter(sex == "Female"), width = 0.5,
                  position = position_dodge()) +
    scale_y_continuous(breaks = seq(-1, 1, 1),
    labels = as.character(c(seq(1, 0, -1), 
                            1))) +
    geom_text(aes(label = neg.val, y = 
                  if_else(sex == "Male", estimate - qnorm(0.95)*std.error+0.2,
                          estimate - qnorm(0.95)*std.error-0.2)), 
            size = 4) +
  coord_flip() + 
  theme_bw() +
  scale_fill_grey()+
  facet_nested(rows = vars(kintype), cols = vars(mort.level, country)) +
  labs(x = "Age", y = "% point difference for all individuals", fill = "Sex",
       title = "Excess Bereavement, March-June 2020") +
  theme(legend.position = "bottom")

ggsave(filename = "~/covid_simulation/Output/paper_figures/high_low_mort_ebr.png", height = 5.5, units = "in")
```

```{r}
#Numbers for probability of loss for the paper
#Max
probloss_compare %>%
  filter(kintype == "Grandparents", sex == "F", age == "30-44") %>%
  arrange(-estimate) %>%
  head(1)

#Min
probloss_compare %>%
  filter(kintype == "Grandparents", sex == "F", age == "30-44") %>%
  arrange(-estimate) %>%
  tail(1)
```

```{r}
#Testing to see if we can make the age profiles
#We'll make them for just females now

probloss_compare %>%
  filter(sex == "F", country %in% c("Sweden","Norway"), type == "excess") %>%
  ggplot() + geom_line(aes(x = as.factor(age), y = estimate, 
                           linetype = kintype, group = kintype)) +
  facet_wrap(~country)+
  labs(x = "Age", y = "% point difference", linetype = "Kin Relation", 
       title = "Age Profiles of Excess Bereavement \nFemale Reference Individuals, March-June 2020") +
  theme_bw()
```

```{r}
#Merging in population figures
require(wpp2019)
```

```{r}
data(popM)
data(popF)
popM$M_2020 <- popM$`2020`
popF$F_2020 <- popF$`2020`

pop_merged <- merge(popM %>% dplyr::select(c(country_code, name, age, M_2020)),
             popF %>% dplyr::select(c(country_code, name, age, F_2020)))
```

```{r}
pop_group <- pop_merged %>%
  pivot_longer(cols = c("M_2020", "F_2020"), 
               names_to = c("sex", "year"), names_sep = "_", 
               values_to = "pop") %>%
  mutate(country = name, 
         age_group = if_else(age %in% c("0-4", "5-9", "10-14"), "0-14", 
           if_else(age %in% c("15-19", "20-24", "25-29"), "15-29",
                   if_else(age %in% c("30-34", "35-39", "40-44"), "30-44", 
                           if_else(age %in% c("45-49", "50-54", "55-59", "60-64"), "45-64", "65+")))))
```

```{r}
pop_final <- pop_group %>%
  group_by(country, age_group, sex) %>%
  summarize(pop = sum(pop)) %>%
  mutate(pop = 1000*pop,
         age = age_group) %>%
  ungroup() %>%
  mutate(age_group = NULL)
```

```{r}
#Now merge this in
probloss_pop <- left_join(probloss_compare, pop_final, by = c("country", "sex", "age")) %>%
  mutate(magnitude = estimate*pop/100)
```

```{r}
#Now for a sanity check: do these numbers look reasonable?
#Compare to the Kidman estimates (37,300 bereaved up till February 2021, aged 0-17--not the same interval as we have)
probloss_pop %>%
  filter(country == "United States of America", kintype == "Parents", 
         age == "0-14", type == "excess") %>%
  summarize(magnitude = sum(magnitude))
#That's around 17,000 children bereaved in the first wave
#Kidman: 0.078 bereaved for each Covid death
#According to OWID, the US had 128171 cumulative COVID deaths July 1, 2020
0.078*128171
#Our number is a good bit higher (although we do account for excess deaths)
#We do, however, only go up to age 14
```

```{r}
#Other plausibility checks
#Do numbers sound plausible?
#Sweden:
probloss_pop %>%
  filter(country == "Sweden", age == "30-44", 
         type == "excess", kintype == "Grandparents") %>%
  summarize(magnitude = sum(magnitude),
            pop = sum(pop))

#7,849 people aged 30-44 lost a grandparent in the first wave
#out of a population of 1.9 million
```
```{r}
#Spain:
probloss_pop %>%
  filter(country == "Spain", age == "30-44", 
         type == "excess", kintype == "Grandparents") %>%
  summarize(magnitude = sum(magnitude),
            pop = sum(pop))
#Meanwhile, the number in Spain is 95,000
#Is this reasonable or too high?
```
```{r}
#Save these numbers as a CSV
probloss_pop %>%
  filter(type == "excess") %>%
  select(c(country, age, sex, kintype, prob_bereaved = estimate, pop, num_bereaved = magnitude)) %>%
  write_csv("~/covid_simulation/Data/magnitudes_test.csv")
```

