---
title: "Checking New Simulations"
output:
  html_document:
    df_print: paged
---

```{r message=FALSE, warning=FALSE}
require(tidyverse)
'%ni%' <- Negate('%in%')
```

```{r}
old_data <- get(load(file = "~/covid_simulation/Data/finaldata_v2.RData"))
new_data <- get(load(file = "~/covid_simulation/Data/finaldata_robustness_check.RData"))
```

```{r}
#Compare death rates
old_deathrates <- old_data$death_rates %>%
  filter(country %in% c("Norway", "Sweden")) %>%
  mutate(source = "old")

new_deathrates <- new_data$death_rates %>%
  mutate(source = "new")

both_deathrates <- bind_rows(new_deathrates, old_deathrates)
```

```{r}
#Compare death rates by age for both categories
#Make sure they're actually normally distributed to run an ANOVA
#We find the 65+ rates are indeed similar to a normal distribution (but others aren't)
#plot an example here
#hist(both_deathrates %>% filter(age == "65+", country == "Norway", scenario == "other", fem == 1) %>% pull(value))

sexes <- rep(c(0,1), each = 4)
scenarios <- rep(c("covid", "other"), times = 4)
countries <- rep(c("Sweden", "Norway"), each = 2, times = 2)
pvalues <- bind_rows(lapply(1:8, function(x) {
anova <- aov(value ~ source, data = both_deathrates %>% 
               filter(age == "65+", scenario == scenarios[x], 
                      country == countries[x], fem == sexes[x]))

pval <- summary(anova)[[1]][["Pr(>F)"]][1]
tibble <- tibble(pval = pval, country = countries[x], scenario = scenarios[x], sex = sexes[x], age = "65+")
}
))

#Note: Is an ANOVA optimal here?
#In only one group is there a statistically significant difference
pvalues
```

```{r}
#Plot this as well
#It mostly seems to check out, although younger age mortality is concerning
both_deathrates %>%
  filter(age %ni% c("all_mid", "all_sum")) %>%
  group_by(fem, age, source, scenario, country) %>%
  summarize(value = mean(value, na.rm = T)) %>%
  pivot_wider(id_cols = c(fem, age, country, scenario), names_from = source, values_from = value) %>%
  mutate(pc_diff = 100*(new - old)/old,
         scenario = str_to_title(scenario),
         fem = if_else(fem == 1, "F", "M")) %>%
  ggplot() + geom_point(aes(x = as.factor(age), y = pc_diff, color = fem)) + 
  facet_grid(rows = vars(scenario), cols = vars(country)) +
  theme_bw() + 
  labs(x = "Age", y = "% difference", color = "Sex")
```

