---
title: "Investigating Spousal Availability in Our Simulations"
output:
  html_document:
    df_print: paged
---

```{r}
require(tidyverse)
require(data.table)
```

```{r}
#Useful functions

#-----negation

'%ni%' <- Negate('%in%')

#-----na values
zna <- function(x){return(ifelse(x==0,NA,x))}


#----asYr

# a function to convert socsim months to calendar years
asYr <- function(FinalSimYear = FinalSimYear, endmo = endmo, x) {
  return(trunc(FinalSimYear - (endmo - x)/12)) #+1) #(removing this)
}

FinalSimYear <- 2035
endmo <- 3420
feb2020 <- 3241
postcovid2020 <- 3246
```

```{r}
load("~/90days/covidRESULTS/SocCovid-mallikasnyder/Sweden:Medium.sup/104464/SimResults/sims.Rsave")
```

```{r}
opop <- sims$opop
omar <- sims$omar
```

## Find spouses, then filter to active marriages

```{r}
#This is the old way we were finding these spouses
opop$spouse_standard<-ifelse(opop$fem,
                      (omar[zna(opop$marid),"hpid"]),
                      (omar[zna(opop$marid),"wpid"]))


opop$m_dstart<-omar[zna(opop$marid),"dstart"]
opop$m_dend<-omar[zna(opop$marid),"dend"]
```

```{r}
std_spouses <- opop %>%
  filter(m_dstart <= feb2020 & m_dend > feb2020)

nrow(std_spouses)
```

## Filter to active marriages, then find spouses from the filtered omar

```{r}
omar_filtered <- sims$omar %>%
  filter(dstart <= feb2020 & dend > feb2020)

opop2 <- sims$opop
```

```{r}
opop2$spouse_filtered<-ifelse(opop2$fem, 
                      omar_filtered$hpid[match(opop$marid, omar_filtered$mid)],
                      omar_filtered$wpid[match(opop$marid, omar_filtered$mid)])
```

```{r}
filtered_spouses <- opop2 %>%
  filter(!is.na(spouse_filtered))
nrow(filtered_spouses)
```

## Now compare spouses located in the two cases

```{r}
#All match--this suggests that this is less likely to be the issue
table(std_spouses$spouse_standard == filtered_spouses$spouse_filtered)
```
