---
title: "Models"
output:
  html_document:
    df_print: paged
---

## Data Preparation

```{r message=FALSE}
#Load functions
#Source functions and packages
source("~/covid_simulation/Kin_death/01_load_functions.R")
source('~/covid_simulation/Kin_death/functions_bereavement.R')

#Require this additional packages
require(broom)
require(countrycode)
require(ggrepel)
require(viridis)
require(kableExtra)

#Load data: currently, this points to the latest version with data for the first wave
data <- get(load(file = "~/covid_simulation/Data/final_data_firstwave_updated.RData"))
```

```{r}
#Find numbers for indices for each country
indices <- data$numbers %>%
  group_by(country) %>%
  summarize(max_index = min(nsims))
```

```{r}
#Burden of bereavement object
kin_ebr <-data$kin_bb %>%
  full_join(., indices, by = c("country" = "country")) %>%
  filter(!is.na(scenario)) %>% 
  mutate(sex = ifelse(grepl("f1", category), "F", "M"),
         age = gsub("f[0-1]{1}", "", category),
         category = NULL) %>%
  ungroup() %>%
  group_by(country, scenario, sex, age, kintype) %>%
  mutate(index = row_number(), category = NULL) %>%
  filter(index <= max_index) %>%
  ungroup() %>%
  pivot_wider(id_cols = c("country", "sex", "age", "kintype", "index"), 
              names_from = "scenario", 
              values_from = c("mean_post_all", "mean_pre_all", "mean_pre_with", "sd_pre_with", "n_withkin", 
                              "mean_post_with", "sd_post_with", "sim.id", "n_losekin", "n_total")) %>%
  mutate(bereavement_covid = (mean_pre_with_covid - mean_post_with_covid),
         bereavement_other = (mean_pre_with_other - mean_post_with_other),
         n_withkin = (n_withkin_covid + n_withkin_other)/2,
         n_total = (n_total_covid + n_total_other)/2,
         pc_withkin = (n_withkin/n_total)*100,
         probloss_covid = 100*(n_losekin_covid/n_withkin_covid),
         probloss_other = 100*(n_losekin_other/n_withkin_other),
         probloss_rel_diff = 100*(probloss_covid - probloss_other)/probloss_other,
         probloss_abs_diff = probloss_covid - probloss_other,
         probloss_abs_diff_adj = probloss_abs_diff*pc_withkin/100,
         probloss_other_adj = (probloss_other*(n_withkin_other/n_total_other))/100,
         ccode = countrycode(gsub("_", " ", country), 
                             origin = 'country.name', destination = 'iso3c'))
```

```{r}
# Kin ratio object
  kin_structure <- data$kin_ratio %>%
    full_join(., indices, by = c("country" = "country")) %>%
    filter(!is.na(scenario)) %>% 
    mutate(sex = ifelse(grepl("f1", category), "F", "M"),
           age = gsub("f[0-1]{1}", "", category),
           category = NULL) %>%
    ungroup() %>%
    group_by(country, scenario, sex, age, kintype) %>%
    mutate(index = row_number(), category = NULL) %>%
    filter(index <= max_index) %>%
    ungroup() %>%
    pivot_wider(id_cols = c("country", "sex", "age", "kintype", "index"), 
                names_from = "scenario", 
                values_from = c("count_all", "sd_all", "count_female", "count_male",
                                "count_65plus", "count_below65", "n_egos", "sim.id")) %>%
    mutate(ccode = countrycode(gsub("_", " ", country), 
                               origin = 'country.name', destination = 'iso3c'),
           count_all_diff = count_all_covid - count_all_other)
```

```{r}
#Death rates object
  death_rates <- data$death_rates %>%
  full_join(., indices, by = c("country" = "country")) %>%
  filter(!is.na(scenario)) %>% 
  mutate(sex = ifelse(fem == 1, "F", "M")) %>%
  ungroup() %>%
  group_by(country, scenario, sex, age) %>%
  mutate(index = row_number(), fem = NULL) %>%
  filter(index <= max_index) %>%
  ungroup() %>%
  pivot_wider(id_cols = c("country", "sex", "age", "index"), 
              names_from = "scenario", 
            values_from = c("n_num", "n_den", "value", "sim.id")) 
```

```{r}
  #Object used for excess mortality analysis
  em <- death_rates %>%
  filter(age %ni% c("all_sum", "all_mid")) %>%
  mutate(age_interval = if_else(age %in% c("0-14"), "0-14", 
         if_else(age %in% c("65+"), "65+", "15-64"))) %>%
  ungroup() %>%
  group_by(index, country, sim.id_covid, sim.id_other, age_interval) %>%
  summarize(n_num_covid = sum(n_num_covid, na.rm = T),
            n_num_other = sum(n_num_other, na.rm = T)) %>%
    mutate(em = 100*((n_num_covid - n_num_other)/n_num_other),
           em = if_else(em == Inf, NaN, em))
```

```{r}
  #Object used for excess mortality analysis
  age_str_indiv <- death_rates %>%
  filter(age %ni% c("all_sum", "all_mid")) %>%
  ungroup() %>%
  group_by(index, country, sim.id_covid, sim.id_other, age, sex) %>%
  summarize(n_den_covid = sum(n_den_covid, na.rm = T),
            n_den_other = sum(n_den_other, na.rm = T)) %>%
    mutate(n_den = (n_den_covid + n_den_other)/2)

age_str_total <- age_str_indiv %>%
  ungroup() %>%
  group_by(index, country, sim.id_covid, sim.id_other, sex) %>%
  summarize(total = sum(n_den))

age_str_15 <- age_str_indiv %>%
  ungroup() %>%
  filter(age %in% c("15-29", "30-44", "45-64")) %>%
  group_by(index, country, sim.id_covid, sim.id_other, sex) %>%
  summarize(total_15 = sum(n_den))

age_str <- merge(age_str_indiv, merge(age_str_total, age_str_15))


age_str <- age_str %>%
  mutate(pc_age = 100*(n_den/total))
```

```{r}
#STMF mortality rates
#Calculate STMF excess mortality based on the code in MakeFactor.R, with modifications
 stmf <- fread("~/covid_simulation/Rcode/stmf-mar9-run.csv", stringsAsFactors = F)

  names(stmf) <- tolower(names(stmf)) #Make names lowercase

  #Keeping countries that only have data for 2020
  keepcountry <- unique(stmf$countrycode[which(stmf$year == 2020)])

  #Pivoting the STMF data into long format
  adj.total <- stmf %>%
    dplyr::select(-c(split, splitsex, forecast)) %>% #removing variables
    filter(countrycode %in% keepcountry) %>%
    pivot_longer(-c(year, week, countrycode, sex), 
                 names_to = c("type", "age"), values_to = "rate", names_sep = 1) %>% #pivoting
    pivot_wider(names_from = "type", values_from = "rate") %>%
    mutate(death_count = d, #renaming and generating new versions of variables
           death_rate = r,
           age = gsub("85p", "85-99", gsub("_", "-", age)),
           age_int = age,
           age = if_else(age_int %ni% c("0-14", "15-64", "total"), "65+", age_int),
           country = countrycode,
           sex = if_else(sex %in% c("f"), "Female", if_else(sex %in% c("m"), "Male", "b"))) %>%
    filter(age %ni% c("total", "0-14"), between(year, 2016, 2020), sex != "b") %>%
    group_by(country, year, week, age) %>%
    summarize(deaths15 = sum(death_count, na.rm = T))
## `summarise()` has grouped output by 'country', 'year'. You can override using the `.groups` argument.
  #STMF currently reports the UK estimate for England and Wales, Scotland, and Northern Ireland separately; we combine them into one country and use that estimate for the UK
  #Seeing if we need to adjust the UK estimate: we see if we have more than one containing the code GBR
  adjustUK <- if_else(length(grep("GBR", levels(as.factor(adj.total$country)))) > 1, T, F)
  
  #Print whether we need to adjust this
  print(paste("UK estimate being constructed from", length(grep("GBR", levels(as.factor(adj.total$country)))), "entities"))

  
  if (adjustUK <- T) {
    #England and Wales, Scotland, and NI may go up to different number of weeks. 
    #Make sure we have the same number of weeks for each
     week_final_uk <-  adj.total %>% 
       filter(grepl("GBR", country), year == 2020) %>%
       ungroup() %>%
       group_by(country) %>%
       summarize(max_week = max(week), .groups = "keep") %>%
       ungroup() %>%
       summarize(min_week = min(max_week)) %>%
       pull(min_week)
    
    #Now construct a single estimate for the UK
    adj.total.uk <- adj.total %>% 
      filter(grepl("GBR", country) & week <= week_final_uk) %>%
      ungroup() %>%
      group_by(year, week, age) %>%
      summarize(deaths15 = sum(deaths15), .groups = "keep") %>% #Adding up UK estimates
      mutate(country = "GBR") #Creating one country code
    
    adj.total2 <- adj.total %>% 
      filter(!grepl("GBR", country)) %>% #Combining them with all other countries in the dataset
      bind_rows(adj.total.uk)
  } else {
    adj.total2 <- adj.total
  }
    
  final_week <- 24
  
  #Now convert weekly data into monthly data
    adj.monthly <- adj.total2 %>%
      filter(week <= final_week) %>% #removing all data after a set cutoff point for comparability between countries
      mutate(month = as.numeric(as.factor(cut(week, breaks = seq(1, final_week+1, by = 4), 
                                              right = FALSE)))) %>%
      ungroup() %>%
      filter(month %in% c(3,4,5,6)) %>%
      group_by(country, year, age) %>%
      summarize(deaths15 = sum(deaths15), .groups = "keep") %>% #generating monthly death counts and exposures
      mutate(period = if_else(year %in% c(2016:2019), "Past", "Current"))
    
  #Making sure this worked
  print(paste("UK estimates still need adjusting: ", if_else(length(grep("GBR", levels(as.factor(adj.monthly$country)))) > 1, T, F)))

 #Now we can generate excess mortality

  adj.past <- adj.monthly %>%  #Calculate average for past 4-year period
    filter(period == "Past") %>%
    ungroup() %>%
    group_by(country, age) %>%
    summarize(mean_past_deaths15 = mean(deaths15))

   adj.current <- adj.monthly %>% filter(period == "Current") %>% #Find current mx values
    ungroup() %>%
    mutate(current_deaths15 = deaths15) %>% 
              dplyr::select(-c(year, deaths15))
  
    #Getting final monthly factors
    adj.monthly.final <- left_join(adj.past, adj.current, #Combine past and current values
                                by = c("country" = "country", "age" = "age")) %>%
      filter(country %ni% c("TWN")) %>% #Removing Taiwan for now
    mutate(mean_past_deaths15 = if_else(mean_past_deaths15 == 0, 10^-6, mean_past_deaths15),
          stmf_em15 = 100*(current_deaths15 - mean_past_deaths15)/mean_past_deaths15,
           country_name =  countrycode(substr(country, 1, 3), origin = "iso3c", destination = "un.name.en"),
           country_name =gsub("United Kingdom of Great Britain and Northern Ireland",
                                      "United Kingdom", country_name))
```

```{r}
pre_merge <- em %>% filter(age_interval == "65+") %>% dplyr::select(-age_interval)
kin_ebr_em <- merge(kin_ebr, pre_merge)
```

### Decomposition 

```{r}
kintype.val <- "gparents"
sex.val <- "F"
age.val <- "30-44"
```

```{r}
data <- kin_ebr_em %>%
  filter(kintype == kintype.val, sex == sex.val, pc_withkin > 1)

model <- by(data, data[, "age"], function(y) lm(probloss_abs_diff_adj ~ em + country, 
                                                data = y, na.action = na.omit))
```

```{r}
summary(model[["30-44"]])
```

This doesn't really work!

```{r}
data <- kin_ebr_em %>%
  filter(kintype == kintype.val, sex == sex.val, age == age.val, pc_withkin > 1)

model <- by(data, data[, "country"], function(y) lm(probloss_abs_diff_adj ~ em, 
                                                data = y, na.action = na.omit))
```

```{r}
summary(model[["Germany"]])
```

```{r}
summary(model[["France"]])
```

